name: Splegg
version: 1.6
main: com.raptorhosting.splegg.Splegg
authors: [njb_said, Raptor-Hosting]
description: Splegg > Spleef using eggs
softdepend: [WorldEdit]
commands:
  splegg:
    description:
    aliases: [sp]